language: go
go_import_path: github.com/LUSHDigital/core-sql

go:
  - 1.13.x
  - tip

sudo: false
install: true

before_script:
  - go get golang.org/x/lint/golint

script:
  - export PATH=$PATH:$HOME/gopath/bin
  - export GORACE="halt_on_error=1"
  - golint -set_exit_status $(go list ./... | grep -v /vendor/)
  - go test -v -race -tags safe ./...
  - go test -v -race -tags testcgo ./... -covermode=atomic -coverprofile=profile.cov

matrix:
  fast_finish: true
  allow_failures:
    - go: tip
